# Generated by Django 2.2.2 on 2019-06-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.CharField(choices=[('OC', 'Ocupado'), ('DI', 'Disponible')], default='DI', max_length=2),
        ),
    ]
