# Generated by Django 2.2.2 on 2019-06-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnero_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prioridad',
            options={'verbose_name': 'Prioridad', 'verbose_name_plural': 'Prioridades'},
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name': 'Servicios', 'verbose_name_plural': 'Servicio'},
        ),
        migrations.AlterModelOptions(
            name='serviciosusuarios',
            options={'verbose_name': 'Servicios de usuarios', 'verbose_name_plural': 'Servicios de usuarios'},
        ),
    ]
