# Generated by Django 2.2.2 on 2019-06-18 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnero_app', '0002_auto_20190618_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosusuarios',
            name='finalizo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviciosusuarios',
            name='prioridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
