# Generated by Django 2.2.2 on 2019-06-18 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turnero_app', '0004_auto_20190618_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosusuarios',
            name='fecha_finalización',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
