# Generated by Django 2.2.2 on 2019-06-18 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnero_app', '0005_auto_20190618_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosusuarios',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviciosusuarios',
            name='prioridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero_app.Prioridad'),
        ),
    ]
