# Generated by Django 2.2.2 on 2019-06-18 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnero_app', '0006_auto_20190618_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviciosusuarios',
            options={'verbose_name': 'Turnos de usuarios', 'verbose_name_plural': 'Turnos de usuarios'},
        ),
        migrations.CreateModel(
            name='ServiciosEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero_app.Servicios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio de empleado',
                'verbose_name_plural': 'Servicios de los empleados',
            },
        ),
    ]
