# Generated by Django 2.2.2 on 2019-06-19 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnero_app', '0008_auto_20190618_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosempleado',
            name='servicicios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero_app.ServiciosUsuarios'),
        ),
        migrations.AlterField(
            model_name='turnosempleados',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_turnos', to=settings.AUTH_USER_MODEL),
        ),
    ]
