# Generated by Django 2.2.2 on 2019-06-19 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnero_app', '0009_auto_20190619_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosempleado',
            name='servicicios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero_app.Servicios'),
        ),
    ]
