# Generated by Django 2.2.2 on 2019-06-19 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnero_app', '0010_auto_20190619_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnosempleados',
            name='inicio',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='serviciosempleado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_empleados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turnosempleados',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
    ]
