# Generated by Django 2.2.2 on 2019-06-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero_app', '0011_auto_20190619_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnosempleados',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
